### ISSUE TITLE
Wrong link to forum?

### ISSUE THREAD

**Issue by chris-lesage** [jrymk/obsidian-tab-key#2]
I might be wrong, and sorry if this is presumptuous. But the link you use in the forum seems quite different to what this plugin does.

I wonder if you actually meant to link to this FR post? https://forum.obsidian.md/t/option-to-disable-tab-to-indent/40868

That was the thread where you first announced this plugin. And it has a much larger discussion including different use cases related to typing tab mid-sentence, or inside bar-codes.)

The Help thread you linked in your description doesn't seem exactly related to your plugin.

Chris (rigmarole)

**Comment by jrymk** [comment]
Ah yes, didn't notice I copied the wrong link, thank you for reminding. I've updated README with the correct forum link.
